name: Update Scoreboard

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update-scoreboard:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.MY_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./scripts

      - name: Run Node.js update script
        run: node update.js
        working-directory: ./scripts
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_KEY }}

      - name: Run PHP script
        run: php scripts/index.php
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_KEY }}
